uart:
  - id: U1
    tx_pin: GPIO17
    rx_pin: GPIO05
    baud_rate: 19200
    parity: EVEN
    stop_bits: 1

modbus:
  - id: modbus1
    uart_id: U1

modbus_controller:
  - address: 0x0001
    id: modbus_user
    update_interval: 10s
    modbus_id: modbus1

text_sensor:
# Registre 0x0064
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    id: etat_circuit_frigo
    name: "État du circuit frigo"
    icon: mdi:valve
    entity_category: diagnostic
    register_type: holding
    address: 0x0064
    raw_encode: HEXBYTES
    lambda: |-
      uint16_t value = modbus::helpers::word_from_hex_str(x, 0);
      switch (value) {
        case 0: return std::string("État initial");
        case 1: return std::string("ECS");
        case 2: return std::string("Air");
        case 3: return std::string("Standby");
        case 4: return std::string("Standby sécurité");
        case 5: return std::string("En cours de modification");
        default: return std::string("Unknown");
      }
      return x;
  # Registre 0x0082
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    id: changement_filtre
    name: "Changement du filtre"
    icon: mdi:air-filter
    entity_category: diagnostic
    register_type: holding
    address: 0x0082
    raw_encode: HEXBYTES
    lambda: |-
      uint16_t value = modbus::helpers::word_from_hex_str(x, 0);
      switch (value) {
        case 0: return std::string("Bon");
        case 1: return std::string("À changer");
        default: return std::string("Unknown");
      }
      return x;

sensor:
# Registre 0x0001
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    id: version_logiciel_regulateur
    name: "Version logiciel régulateur"
    icon: mdi:package
    entity_category: diagnostic
    register_type: holding
    address: 0x0001
    value_type: U_WORD
  # Registre 0x0010
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    id: date_et_heure
    name: "Date et heure"
    icon: mdi:calendar-clock
    device_class: timestamp
    entity_category: diagnostic
    register_type: holding
    address: 0x0010
    value_type: U_DWORD
    filters:
      - offset: 229413106
  # Registre 0x0078
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    id: temperature_piece_principale
    name: "Température pièce principale"
    icon: mdi:thermometer
    device_class: temperature
    state_class: measurement
    register_type: holding
    address: 0x0078
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

number:
# Registre 0x0096
  - &thermostat
    platform: modbus_controller
    modbus_controller_id: modbus_user
    id: thermostat_k1a
    name: "Thermostat ${K1a}"
    icon: mdi:thermostat
    unit_of_measurement: "°C"
    address: 0x0096
    value_type: U_WORD
    min_value: 0
    max_value: 31
    multiply: 100
# Registre 0x0097
  - <<: *thermostat
    id: thermostat_k1b
    name: "Thermostat ${K1b}"
    address: 0x0097
# Registre 0x0098
  - <<: *thermostat
    id: thermostat_k2
    name: "Thermostat ${K2}"
    address: 0x0098
  # Registre 0x0099
  - <<: *thermostat
    id: thermostat_k3
    name: "Thermostat ${K3}"
    address: 0x0099
  # Registre 0x009A
  - <<: *thermostat
    id: thermostat_k4
    name: "Thermostat ${K4}"
    address: 0x009A
  # Registre 0x009B
  - <<: *thermostat
    id: thermostat_k5
    name: "Thermostat ${K5}"
    address: 0x009B
  # Registre 0x009C
  - <<: *thermostat
    id: thermostat_k6
    name: "Thermostat ${K6}"
    address: 0x009C
  # Registre 0x009D
  - <<: *thermostat
    id: thermostat_k7
    name: "Thermostat ${K7}"
    address: 0x009D
  # Registre 0x009E
  - <<: *thermostat
    id: thermostat_k8
    name: "Thermostat ${K8}"
    address: 0x009E
  # Registre 0x009F
  - <<: *thermostat
    id: thermostat_k9
    name: "Thermostat ${K9}"
    address: 0x009F
  # Registre 0x00A0
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    id: tarif_hp
    name: "Tarif HP"
    icon: mdi:currency-eur
    entity_category: config
    mode: box
    unit_of_measurement: "€"
    address: 0x00A0
    value_type: U_WORD
    min_value: 0.05
    max_value: 1
    multiply: 1000
    step: 0.001
# Registre 0x00A1
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    id: tarif_hc
    name: "Tarif HC"
    icon: mdi:currency-eur
    entity_category: config
    mode: box
    unit_of_measurement: "€"
    address: 0x00A1
    value_type: U_WORD
    min_value: 0.05
    max_value: 1
    multiply: 1000
    step: 0.001
# Supprime les canaux non utilisées (Solution pour le 'null')
  - id: !remove ${nombre_thermostats | int < 2 and "thermostat_k2"}
  - id: !remove ${nombre_thermostats | int < 3 and "thermostat_k3"}
  - id: !remove ${nombre_thermostats | int < 4 and "thermostat_k4"}
  - id: !remove ${nombre_thermostats | int < 5 and "thermostat_k5"}
  - id: !remove ${nombre_thermostats | int < 6 and "thermostat_k6"}
  - id: !remove ${nombre_thermostats | int < 7 and "thermostat_k7"}
  - id: !remove ${nombre_thermostats | int < 8 and "thermostat_k8"}
  - id: !remove ${nombre_thermostats | int < 9 and "thermostat_k9"}

select:
# Registre 0x007A
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    id: mode_air
    name: "Mode air"
    icon: mdi:air-conditioner
    entity_category: config
    address: 0x007A
    value_type: U_WORD
    optionsmap:
      "Off": 0
      "Confort Chauffage": 1
      "Eco Chauffage": 2
      "Prog A Chauffage": 3
      "Prog B Chauffage": 4
      "Confort Clim" : 5
      "Boost Clim" : 6
      "Prog C Clim" : 7
      "Prog D Clim" : 8
      "Ventilation" : 9
