sensor:
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    id: volume_restant_ecs
    name: "Volume restant ECS"
    icon: mdi:hydraulic-oil-level
    device_class: volume
    state_class: total
    register_type: holding
    address: 0x006E
    value_type: U_WORD
    unit_of_measurement: "L"
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    id: temperature_ecs
    name: "Température ECS"
    icon: mdi:water-thermometer-outline
    device_class: temperature
    state_class: measurement
    register_type: holding
    address: 0x0070
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

number:
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    id: consigne_ecs
    name: "Consigne ECS"
    icon: mdi:thermostat
    entity_category: config
    register_type: holding
    address: 0x006F
    value_type: S_WORD
    step: 0.1
    min_value: 7
    max_value: 61
    use_write_multiple: true
    unit_of_measurement: "°C"
    multiply: 100
  
select:
  - platform: modbus_controller
    modbus_controller_id: modbus_user
    id: mode_ecs
    name: "Mode ECS"
    icon: mdi:water-boiler
    entity_category: config
    address: 0x0071
    value_type: U_WORD
    use_write_multiple: true
    optionsmap:
      "Off": 0
      "On": 1
      "Boost": 2
